---
title: "HPC Time courses"
author: "Catherine Walsh"
date: "11/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r import data, scripts and libraries}

library(R.matlab)
library(dplyr)
library(reshape2)
library(ggplot2)
library(psych)
library(plotly)
library(patchwork)

load('data/behav.RData')
load('data/split_groups_info.RData')

source('helper_fxns/load_in_ROI.R')
source('helper_fxns/split_TC_into_groups.R')
source('helper_fxns/create_TC_for_plot.R')
source('helper_fxns/load_effect_corr.R')
source('helper_fxns/prep_TC_corr_for_plot.R')
source('helper_fxns/plot_TC_corrs_indiv_ROIs.R')

# these times are based on when the actual cues were on the screen 
rects <- data.frame(xstart=c(0,2.5,10),xend=c(2.5,10,12),col = factor(c("cue","delay","probe"),levels=c("cue","delay","probe")))

# adjust for hemodynamic delay 
rects$xstart <- rects$xstart+5
rects$xend <- rects$xend+5

```

```{r load in time courses}

HPC_ROI_list <- c("LeftHPC_Ant", "RightHPC_Ant", "LeftHPC_Med", "RightHPC_Med", "LeftHPC_Post", "RightHPC_Post")
HPC_TCs <- load_in_ROI(basepath = "data/HPC_Ant_Med_Post/", HPC_ROI_list)

```

```{r prep for plotting}

allSubjs <- constructs_fMRI$PTID
HPC_TC_groups <- split_TC_into_groups(HPC_TCs,WM_groups,allSubjs)
HPC_TC_for_plot <- create_TC_for_plot(HPC_TC_groups)


```

```{r plot L1 vs L3}


for (ROI in seq.int(1,length(HPC_TCs))){
  print(ggplot(data=HPC_TCs[[ROI]]$avg)+
          geom_rect(data=rects,aes(xmin=xstart, xmax=xend, ymin = -Inf, ymax=Inf, fill=col, alpha =0.005),show.legend = FALSE)+
          geom_line(aes(x=Time,y=L1),size=1) +
          geom_line(aes(x=Time,y=L3),size=1,color="red")+
          ylab("Mean Activity") +
          ggtitle(paste("L3 vs L1",names(HPC_TCs)[ROI]))+
          ylim(c(-.4,.5))  
  )
}

```
```{r plot TC by WM group for cue}

for (ROI in seq.int(1,length(HPC_TC_for_plot))){
  print(ggplot(data=HPC_TC_for_plot[[ROI]][["long"]])+
          geom_rect(data=rects,aes(xmin=xstart, xmax=xend, ymin = -Inf, ymax=Inf, fill=col,alpha =0.005),show.legend = FALSE)+
          geom_line(data=HPC_TC_for_plot[[ROI]][["long"]] %>% filter(load=="L3"),aes(x=Time,y=Mean,color=level),size=1) +
          geom_line(data=HPC_TC_for_plot[[ROI]][["long"]] %>% filter(load=="L1"),aes(x=Time,y=Mean,color=level),size=1,linetype="dotted")+
          #geom_ribbon(data=HPC_TC_for_plot[[ROI]][["long"]] %>% filter(load=="L3"), aes(x=Time,ymin=SE_min,ymax=SE_max,fill=level),alpha=0.2)+
          #geom_ribbon(data=HPC_TC_for_plot[[ROI]][["long"]] %>% filter(load=="L1"), aes(x=Time,ymin=SE_min,ymax=SE_max,fill=level),alpha=0.2)+
          ylab("Mean Activity") +
          ggtitle(paste("L3 vs L1",names(HPC_TCs)[ROI]))+
          ylim(c(-.4,.5))  
  )
}


```


```{r load effects}

for (ROI in seq.int(1,length(HPC_TC_for_plot))){
  print(ggplot(data=HPC_TC_for_plot[[ROI]][["long"]])+
          geom_rect(data=rects,aes(xmin=xstart, xmax=xend, ymin = -Inf, ymax=Inf, fill=col,alpha =0.005),show.legend = FALSE)+
          geom_line(data=HPC_TC_for_plot[[ROI]][["long"]] %>% filter(load=="LE"),aes(x=Time,y=Mean,color=level),size=1) +
          ylab("Mean Load Effect") +
          geom_ribbon(data=HPC_TC_for_plot[[ROI]][["long"]] %>% filter(load == "LE") %>% filter(level=="high"),aes(x=Time,ymin=SE_min, ymax=SE_max),alpha=.2,linetype=2,fill="red")+
          geom_ribbon(data=HPC_TC_for_plot[[ROI]][["long"]] %>% filter(load == "LE") %>% filter(level=="med"),aes(x=Time,ymin=SE_min, ymax=SE_max),alpha=.2,linetype=2,fill="green")+
          geom_ribbon(data=HPC_TC_for_plot[[ROI]][["long"]] %>% filter(load == "LE") %>% filter(level=="low"),aes(x=Time,ymin=SE_min, ymax=SE_max),alpha=.2,linetype=2,fill="blue")+
          ggtitle(paste("Load effects",names(HPC_TCs)[ROI]))+
          ylim(c(-.4,.5))  
  )
}
```

```{r}

HPC_TC_corr <- load_effect_corr(HPC_TCs,constructs_fMRI$omnibus_span_no_DFR)
HPC_LE_TC_corr_for_plot <- prep_TC_corr_for_plot(HPC_TC_corr,12)

HPC_LE <- ggplot(data=HPC_LE_TC_corr_for_plot) +
  geom_polygon(data=datapoly,aes(x=x,y=y, fill=value,group=id),show.legend =FALSE)+
  geom_line(aes(x=Time,y=correlation,color=ROI),size=1)+
  geom_line(aes(x=Time,y=0.127),size=1,color="red", linetype="dotted")+
  geom_line(aes(x=Time,y=-0.127),size=1,color="red", linetype="dotted")+
  ylab("Correlation") +
  ggtitle("HPC correlation with omnibus span - LE")

ggplotly(HPC_LE)

```

Here, we're extracting the average of 4-6s for the encoding period, and 9-11s for the delay period. The only linear correlation was in the posterior HPC on the left (r = -0.18) during the delay period. 

```{r correlate LE HPC with span at encoding and delay}
 
HPC_Ant_L_LE <- read.csv("data/HPC_Ant_Med_Post/Left_Ant_LE.csv")
HPC_Ant_R_LE <- read.csv("data/HPC_Ant_Med_Post/Right_Ant_LE.csv")
HPC_Med_L_LE <- read.csv("data/HPC_Ant_Med_Post/Left_Med_LE.csv")
HPC_Med_R_LE <- read.csv("data/HPC_Ant_Med_Post/Right_Med_LE.csv")
HPC_Post_L_LE <- read.csv("data/HPC_Ant_Med_Post/Left_Post_LE.csv")
HPC_Post_R_LE <- read.csv("data/HPC_Ant_Med_Post/Right_Post_LE.csv")

HPC_LEs <- cbind(HPC_Ant_L_LE, HPC_Ant_R_LE, HPC_Med_L_LE, HPC_Med_R_LE, HPC_Post_L_LE, HPC_Post_R_LE)
colnames(HPC_LEs) <- c("Ant_L_enc","Ant_L_delay", "Ant_R_enc","Ant_R_delay", "Med_L_enc","Med_L_delay", "Med_R_enc", "Med_R_delay","Post_L_enc", "Post_L_delay", "Post_R_enc", "Post_R_delay")

HPC_LEs$span <- constructs_fMRI$omnibus_span_no_DFR[c(1:10, 12:170)]

for (HPC in seq.int(1,12)){
  print(colnames(HPC_LEs)[HPC])
  print(cor.test(HPC_LEs$span, HPC_LEs[,HPC]))
  print(ggplot(data = HPC_LEs, aes_string(x="span", y = colnames(HPC_LEs)[HPC]))+
    geom_point()+
    stat_smooth(method="lm")+
    theme_classic()+
    theme(aspect.ratio=1))+
    xlab("Omnibus Span (no DFR measures)")+
    ylab(colnames(HPC_LEs)[HPC])
  
}

```