% RDoC_BetaSeries_Do_lssCorrelation
subjects_with_no_MPRAGE = [1024];
disp(['nb: No MPRAGE aquired for ID1024']);


from = pwd;
try
    run('../../scripts/server_check/RDoC_serve_check.m');
catch
    run('RDoC_serve_check.m');
end

% Directory for the new model. If it does not exist, it will be created.
stdir = [root,'subjects/'];
modeldir = [root,'subjects/'];
betadir  = [root,'scripts/fmri/BetaSeries/'];
maskdir = [root,'Catherine/Schaefer400_7Network_ROI/'];
walshdir = [root,'Catherine/walsh_scripts/'];

% THIS IS THE MODEL TO USE

addpath(betadir);
addpath('/u/project/rbilder/RDoC/Catherine/walsh_scripts');

%addpath(betadir);

%% USER INFORMATION

themodeltouse = 'DFR_Art_Model2';

% NEW ROIs // HPC+FreeSurfer+Localizer+Collin et al.
% 29 ROIs total

RoiListGroup = {...
      '127_7Networks_LH_Cont_Par_1',...
      '128_7Networks_LH_Cont_Par_2',...
      '129_7Networks_LH_Cont_Par_3',...
      '130_7Networks_LH_Cont_Par_4',...
      '131_7Networks_LH_Cont_Par_5',...      
      '132_7Networks_LH_Cont_Par_6',...
      '133_7Networks_LH_Cont_Temp_1',...
      '134_7Networks_LH_Cont_PFCl_1',...
      '135_7Networks_LH_Cont_PFCl_2',...
      '136_7Networks_LH_Cont_PFCl_3',...
      '137_7Networks_LH_Cont_PFCl_4',...
      '138_7Networks_LH_Cont_PFCl_5',...
      '139_7Networks_LH_Cont_PFCl_6',...
      '140_7Networks_LH_Cont_PFCl_7',...
      '141_7Networks_LH_Cont_PFCl_8',...
      '142_7Networks_LH_Cont_PFCl_9',...
      '143_7Networks_LH_Cont_PFCv_1',...
      '144_7Networks_LH_Cont_pCun_1',...
      '145_7Networks_LH_Cont_pCun_2',...
      '146_7Networks_LH_Cont_Cing_1',...
      '147_7Networks_LH_Cont_Cing_2',...
      '148_7Networks_LH_Cont_PFCmp_1',...
      '332_7Networks_RH_Cont_Par_1',...
      '333_7Networks_RH_Cont_Par_2',...
      '334_7Networks_RH_Cont_Par_3',...
      '335_7Networks_RH_Cont_Par_4',...
      '336_7Networks_RH_Cont_Par_5',...
      '337_7Networks_RH_Cont_Par_6',...
      '338_7Networks_RH_Cont_Temp_1',...
      '339_7Networks_RH_Cont_Temp_2',...
      '340_7Networks_RH_Cont_PFCv_1',...
      '341_7Networks_RH_Cont_PFCl_1',...
      '342_7Networks_RH_Cont_PFCl_2',...
      '343_7Networks_RH_Cont_PFCl_3',...
      '344_7Networks_RH_Cont_PFCl_4',...
      '345_7Networks_RH_Cont_PFCl_5',...
      '346_7Networks_RH_Cont_PFCl_6',...
      '347_7Networks_RH_Cont_PFCl_7',...
      '348_7Networks_RH_Cont_PFCl_8',...
      '349_7Networks_RH_Cont_PFCl_9',...
      '350_7Networks_RH_Cont_PFCl_10',...
      '351_7Networks_RH_Cont_PFCl_11',...
      '352_7Networks_RH_Cont_PFCl_12',...
      '353_7Networks_RH_Cont_PFCl_13',...
      '354_7Networks_RH_Cont_PFCl_14',...
      '355_7Networks_RH_Cont_PFCl_15',...
      '356_7Networks_RH_Cont_pCun_1',...
      '357_7Networks_RH_Cont_pCun_2',...
      '358_7Networks_RH_Cont_Cing_1',...
      '359_7Networks_RH_Cont_Cing_2',...
      '360_7Networks_RH_Cont_PFCmp_1',...
      '361_7Networks_RH_Cont_PFCmp_2',...
      '149_7Networks_LH_Default_Temp_1',...
      '150_7Networks_LH_Default_Temp_2',...
      '151_7Networks_LH_Default_Temp_3',...
      '152_7Networks_LH_Default_Temp_4',...
      '153_7Networks_LH_Default_Temp_5',...
      '154_7Networks_LH_Default_Temp_6',...
      '155_7Networks_LH_Default_Temp_7',...
      '156_7Networks_LH_Default_Temp_8',...
      '157_7Networks_LH_Default_Temp_9',...
      '158_7Networks_LH_Default_Temp_10',...
      '159_7Networks_LH_Default_Temp_11',...
      '160_7Networks_LH_Default_Temp_12',...
      '161_7Networks_LH_Default_Temp_13',...
      '162_7Networks_LH_Default_Temp_14',...
      '163_7Networks_LH_Default_Temp_15',...
      '164_7Networks_LH_Default_Temp_16',...
      '165_7Networks_LH_Default_Temp_17',...
      '166_7Networks_LH_Default_PFC_1',...
      '167_7Networks_LH_Default_PFC_2',...
      '168_7Networks_LH_Default_PFC_3',...
      '169_7Networks_LH_Default_PFC_4',...
      '170_7Networks_LH_Default_PFC_5',...
      '171_7Networks_LH_Default_PFC_6',...
      '172_7Networks_LH_Default_PFC_7',...
      '173_7Networks_LH_Default_PFC_8',...
      '174_7Networks_LH_Default_PFC_9',...
      '175_7Networks_LH_Default_PFC_10',...
      '176_7Networks_LH_Default_PFC_11',...
      '177_7Networks_LH_Default_PFC_12',...
      '178_7Networks_LH_Default_PFC_13',...
      '179_7Networks_LH_Default_PFC_14',...
      '180_7Networks_LH_Default_PFC_15',...
      '181_7Networks_LH_Default_PFC_16',...
      '182_7Networks_LH_Default_PFC_17',...
      '183_7Networks_LH_Default_PFC_18',...
      '184_7Networks_LH_Default_PFC_19',...
      '185_7Networks_LH_Default_PFC_20',...
      '186_7Networks_LH_Default_PFC_21',...
      '187_7Networks_LH_Default_PFC_22',...
      '188_7Networks_LH_Default_PFC_23',...
      '189_7Networks_LH_Default_PFC_24',...
      '190_7Networks_LH_Default_PCC_1',...
      '191_7Networks_LH_Default_PCC_2',...
      '192_7Networks_LH_Default_PCC_3',...
      '193_7Networks_LH_Default_PCC_4',...
      '194_7Networks_LH_Default_PCC_5',...
      '195_7Networks_LH_Default_PCC_6',...
      '196_7Networks_LH_Default_PCC_7',...
      '197_7Networks_LH_Default_PCC_8',...
      '198_7Networks_LH_Default_PCC_9',...
      '199_7Networks_LH_Default_PCC_10',...
      '200_7Networks_LH_Default_PCC_11',...
      '362_7Networks_RH_Default_Par_1',...
      '363_7Networks_RH_Default_Par_2',...
      '364_7Networks_RH_Default_Par_3',...
      '365_7Networks_RH_Default_Par_4',...
      '366_7Networks_RH_Default_Par_5',...
      '367_7Networks_RH_Default_Temp_1',...
      '368_7Networks_RH_Default_Temp_2',...
      '369_7Networks_RH_Default_Temp_3',...
      '370_7Networks_RH_Default_Temp_4',...
      '371_7Networks_RH_Default_Temp_5',...
      '372_7Networks_RH_Default_Temp_6',...
      '373_7Networks_RH_Default_Temp_7',...
      '374_7Networks_RH_Default_Temp_8',...
      '375_7Networks_RH_Default_PFCv_1',...
      '376_7Networks_RH_Default_PFCv_2',...
      '377_7Networks_RH_Default_PFCv_3',...
      '378_7Networks_RH_Default_PFCv_4',...
      '379_7Networks_RH_Default_PFCm_1',...
      '380_7Networks_RH_Default_PFCm_2',...
      '381_7Networks_RH_Default_PFCm_3',...
      '382_7Networks_RH_Default_PFCm_4',...
      '383_7Networks_RH_Default_PFCm_5',...
      '384_7Networks_RH_Default_PFCm_6',...
      '385_7Networks_RH_Default_PFCm_7',...
      '386_7Networks_RH_Default_PFCm_8',...
      '387_7Networks_RH_Default_PFCm_9',...
      '388_7Networks_RH_Default_PFCm_10',...
      '389_7Networks_RH_Default_PFCm_11',...
      '390_7Networks_RH_Default_PFCm_12',...
      '391_7Networks_RH_Default_PFCm_13',...
      '392_7Networks_RH_Default_PCC_1',...
      '393_7Networks_RH_Default_PCC_2',...
      '394_7Networks_RH_Default_PCC_3',...
      '395_7Networks_RH_Default_PCC_4',...
      '396_7Networks_RH_Default_PCC_5',...
      '397_7Networks_RH_Default_PCC_6',...
      '398_7Networks_RH_Default_PCC_7',...
      '399_7Networks_RH_Default_PCC_8',...
      '400_7Networks_RH_Default_PCC_9'...
    };

RoiListIndiv = {...
    'mask_LeftHPC_Ant_ID',...
    'mask_LeftHPC_Med_ID',...
    'mask_LeftHPC_Post_ID',...
    'mask_RightHPC_Ant_ID',...
    'mask_RightHPC_Med_ID',...
    'mask_RightHPC_Post_ID',...
    'mask_L_FFA_ID',...
    'mask_R_FFA_ID'...
    };




% OLD

% RoiListGroup = {'mask_R_DLPFC','mask_L_DLPFC','mask_R_IFJ','mask_L_IFJ', 'mask_R_FEF','mask_L_FEF','mask_R_IPS','mask_L_IPS','mask_SMA','mask_L_anterior_MFG','mask_L_Striatum','mask_R_Striatum'};

% RoiListIndiv = {'mask_L_FFA_ID','mask_R_FFA_ID','mask_LeftHPC_ID','mask_RightHPC_ID'};


% load existing data analysis
try
    load([walshdir,themodeltouse,'_Correlation_Yeo_suj_done.mat']);
catch
    suj_done = [];
end

% check for subject list

cd(stdir);
dirs = dir;
suj_list = [];

for i=1:length(dirs)
    if (dirs(i).isdir==1&length(dirs(i).name)==6&~isempty(findstr(dirs(i).name,'ID')))
        
        % check if the model has been tested
        if isdir([dirs(i).name,'/analysis/fMRI/SPM/',themodeltouse,'/BetaSeries'])
            suj_list(end+1) = str2num(dirs(i).name(3:6));
        else
            disp(['Subject" ', dirs(i).name,' has not been preprocessed for BetaSeries']);
        end
    end
end

% exclude the subject already done
suj_list = setdiff(suj_list,[suj_done subjects_with_no_MPRAGE]);

stop = 0;


%disp('DEBUGGING MODE... DELETE LINE 72 for NORMAL RUN');
%suj_list = [1001];



% check for individual ROIs processed
for i=1:length(suj_list)
    for j=1:length(RoiListGroup)
        if exist([maskdir,RoiListGroup{j},'.nii'],'file')~=2
            disp([maskdir,RoiListGroup{j},'.nii']);
            disp('ROIs for group are missing');
            disp('Please check and launch RDoC_Gen_Common_Mask.m first');
            stop = 1;
        end
    end
    test_suj = 0;
    for j=1:length(RoiListIndiv)
        if exist([betadir,'individual_masks/',RoiListIndiv{j},num2str(suj_list(i)),'.nii'],'file')~=2
            stop = 1;
            test_suj = 1;
        end
    end
    if test_suj == 1
        disp(['ROIs for ID', num2str(suj_list(i)),' is missing']);
    end
end


if stop==1
    disp('Please launch RDoC_Gen_Individual_Mask.m first');
    % stop
else
    
    disp('The subject list that will be processed is:');
    disp(suj_list')
    
    addpath(betadir);
    for i=1:length(suj_list)
        
        % need to load individual images and rois
        rois = '';
        for k1=1:length(RoiListGroup)
            rois{end+1} = [maskdir,RoiListGroup{k1},'.nii'];
        end
        for k1=1:length(RoiListIndiv)
            rois{end+1} = [betadir,'individual_masks/',RoiListIndiv{k1},num2str(suj_list(i)),'.nii'];
        end
        images = [];
        %try
        load([stdir,'ID',num2str(suj_list(i)),'/analysis/fMRI/SPM/',themodeltouse,'/BetaSeries/Images.mat']);
        
        % exclude the ACC = 0 images;
        ex_indx = [];
        for ex=1:length(images)
            [~,im_name] = fileparts(images{ex}{1});
            if ~isempty(strfind(im_name,'Acc0'))
                ex_indx = [ex_indx,ex];
            end
        end
        images(ex_indx) = [];
        
        
        % correct images for new server:
        for nserve=1:length(images)
           images{nserve}{1} = strrep(images{nserve}{1},'/space/raid5/data/bilder/RDoC/','/u/project/rbilder/RDoC/');
        end
        
        % ROI 2 ROI ANALYSIS
        settings.fConnType = 'roi2roi';
        settings.overwrite = 1;
        lssCorrelation_CW(images, rois, settings);
        disp(['Subject ROI 2 ROI analysis done: ID',num2str(suj_list(i))]);
        save([walshdir,themodeltouse,'_Correlation_Yeo_suj_done.mat'],'suj_done');
        
%         % ROI 2 VOXELL ANALYSIS
%         settings.fConnType = 'seed2voxel';
%         settings.overwrite = 1;
%         lssCorrelation_CW(images, rois, settings);
%         disp(['Subject ROI 2 voxel analysis done: ID',num2str(suj_list(i))]);
%         suj_done = [suj_done,suj_list(i)];
%         save([betadir,themodeltouse,'_Correlation_Yeo_suj_done.mat'],'suj_done');
%         %catch
%         %    disp([stdir,'ID',num2str(suj_list(i)),'/analysis/fMRI/SPM/',themodeltouse,'/BetaSeries/Images.mat not found']);
%         %end
    end
end


rmpath(betadir);